### ISSUE TITLE
Implementing functionality to use GFW Data API for raster download

### ISSUE THREAD

**Issue by goergen95** [mapme-initiative/mapme.biodiversity#1]
We should evaluate which resources for our indicators are available on the GFW API. We then can decide if it is worth a shot to implement a general-use download functionality for that API.

**Comment by Ohm-Np** [comment]
_The below listed variables are currently available (as fully processed) in the mapme protected areas portfolio:_

|variables|source|temporal coverage|available in GFW|Remarks|
|----------|-------|---------------------|------------------|----------|
|net forest carbon flux|global forest watch| 2001-2019|Y|-|
|forest cover|global forest watch|2000-2020|Y|-|
|forest coverloss|global forest watch|2000-2020|Y|-|
|co2 emission|global forest watch|2000-2020|Y|-|
|ecoregions|wwf|2001|Y|-|
|mangrove extent|gmw|1996, 2007-2010, 2015, 2016|Y|available for years 1996 & 2016|
|copernicus land cover|ESA|2015-2019|Y|available only for year 2015|
|climatic variables (temp, prec)|world clim|1970-2000 & 2000-2018|Y|need to dive more to study this data|
|population count|Worldpop|2000-2020|N|-|
|terrain ruggedness index|SRTM|cross-sectional|N|-|
|accessibility to cities|figshare|2015|N|-|
|clay content in the soil|OpenLandMap|1950-2017|N|-|
|drought indicator|NASA grace|2003-present|N|-|

_The variables which are yet to process but are important:_

|variables|source|available in GFW|Remarks|
|----------|---------------------|------------------|----------|
|burned areas|MODIS|Y|-|

**Comment by goergen95** [comment]
Great, thanks. That is 9/14 resources that would be available via GFW. Also on that platform there are a lot of additional data sets if we think about new indicators in the future and there is also the possibility that they will add new data in the future. In that way I think it would be worth to at least program some functionality to interact with the API to download datasets.

**Comment by goergen95** [comment]
I have started with some functionality to interact with the API. My idea would be to hand this over to you so you can incorporate it for writing a download routine.

**Comment by Jo-Schie** [comment]
hey @Ohm-Np.I  just as mentioned to Darius on the phone. For those datasets where we expect regular updates I think it is better to use the original API, since GFW may not always keep everything up to date on their end. Especially data that are  not in their own core product suite. So for Copernicus, please use the original API of Copernicus to interface (I think you alreay created a routine for that). For Worldclim I think there is no API and at the moment no updates, right? 

Using Worldclim in general will  depend on very much if they plan to update their data, which is currently only until 2018. as for this data, do you know some alternative @goergen95 , that also covers 2019,2020 and 2021 and is regularly updated (temperature and precipitation, globally). 

As for the core GFW datasets where the source is GFW itself, I think an API interface makes definitely sense.

**Comment by Jo-Schie** [comment]
as for [copernicus land service ](https://land.copernicus.eu/)I just saw, that there is already a package in R with an API that we can take advantage of. See [here](https://cran.r-project.org/web/packages/RCGLS/RCGLS.pdf). In cases like that I would vote for not reinventing the wheel and instead just focussing on developing the processing functions in R that work with locally saved data. The tutorial may then contain an example on how to download the data with this package... What do you thinkg @goergen95?

**Comment by goergen95** [comment]
@Ohm-Np, please see @Jo-Schie's comment above and check if the package is suitable for the LCC download.

**Comment by goergen95** [comment]
Hi @Ohm-Np, please revise the [milestone description](https://github.com/mapme-initiative/mapme.biodiversity/milestone/2) for slightly changes requirements for the specific get_resource functionality. Also, please see concrete impelentations [here](https://github.com/mapme-initiative/mapme.biodiversity/blob/main/R/get_treecover.R) and [here](https://github.com/mapme-initiative/mapme.biodiversity/blob/main/R/get_lossyear.R)

**Comment by Jo-Schie** [comment]
Dear @goergen95 and @Ohm-Np . 
I think we need a further specification of where we need APIs or automatic downloads and where we do not need them. So I checked the data and did a little research:

**Own APIs for development**:

- [ ] Global Forest Watch. **Must Variables**: Forest Area, Lossyear, Emissions. If the **other datasets** which are listed above are also downloadable, fine. That helps everyone who would otherwise need to download them manually.  

@goergen95 will be reposnible for this implementation according to the agreements. 

**APIs for which there are already existing packages with reliable APIs**: 
For these data-sources i think the packages should be suggested during the installation process. 

- [ ] API to the ESA landcover data. See [here](https://cran.r-project.org/web/packages/RCGLS/RCGLS.pdf)
- [ ] API to elevation data. See [here](https://cran.r-project.org/web/packages/elevatr/vignettes/introduction_to_elevatr.html)
- [ ] API for rainfall data. See [here](https://cran.r-project.org/web/packages/chirps/index.html)

**The following data do not need an API.**
Download locations should be documented in the Package description/tutorial. 

- [ ] Accessibility

For the following datasets it would be nice if you @Ohm-Np could research more on available packages or APIs and report back here:

- [ ] Worldpop
- [ ] Clay content (@goergen95 : there as another data you mentioned, right?)
- [ ] elevation/TRI
- [ ] Drought indicator (might be obsolete if the rainfall data can subsitute that. What do you think @goergen95 ?)
- [ ] Burned Areas / Fire Alerts

**Comment by goergen95** [comment]
I am closing here since with 028cad60875267a9e745081449e8964ad05480ae all download functions of above mentioned indicators have been implemented and merged to main in a first verions.
