### ISSUE TITLE
Different behaviour of indicator calculation after relocating resource raster files

### ISSUE THREAD

**Issue by Shirobakaidou** [mapme-initiative/mapme.biodiversity#130]
Could you please open a new issue with more information (e.g. error messages) and ideally minimal reproducible examples for the indicators where the above mentioned approach does not work?

_Originally posted by @goergen95 in https://github.com/mapme-initiative/mapme.biodiversity/issues/92#issuecomment-1398177264_
     
The calculation of the indicator `biome` works normally after the resource files are relocated (the same for `ecoregion` and `mangroves_area`), but other indicators (e.g. `soilproperties`) yield errors by fetching resource files from old file path.

```r
library(sf)
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 7.0.0; sf_use_s2() is TRUE
library(mapme.biodiversity)

dir1 <- file.path(tempdir(), "dir1")
dir2 <- file.path(tempdir(), "dir2")
dir.create(dir1)
dir.create(dir2)

aoi <- read_sf(system.file("extdata", "sierra_de_neiba_478140_2.gpkg",
                           package = "mapme.biodiversity"))
aoi <- init_portfolio(
  x = aoi,
  years = 2015:2020,
  outdir = dir1,
  tmpdir = tempdir(),
  cores = 4,
  verbose = TRUE
) 

portfolio1 <- get_resources(
  aoi, 
  resources = "soilgrids",
  layers = "clay", 
  depths = "0-5cm", 
  stats = "mean"
)
#> Starting process to download resource 'soilgrids'........
#> Starting to download data for layer 'clay', depth '0-5cm', and stat 'mean'. This may take a while...
portfolio2 <- get_resources(aoi, resources = "teow")
#> Starting process to download resource 'teow'........

# move resources to a new location
resources <- list.files(dir1, full.names = TRUE)
file.copy(resources, dir2, recursive = TRUE)
#> [1] TRUE TRUE
# remove old location
unlink(resources, recursive = TRUE)

aoi <- init_portfolio(
  x = aoi,
  years = 2015:2020,
  outdir = dir2,
  tmpdir = tempdir(),
  cores = 4,
  verbose = TRUE
) 
#> Found a column named 'assetid'. Overwritting its values with a unique identifier.

calc_indicators(aoi, "soilproperties", stats_soil = c("mean", "median"), engine = "extract")
#> Warning in new_CppObject_xp(fields$.module, fields$.pointer, ...): GDAL Error
#> 4: /tmp/RtmpgGXl0F/dir1/soilgrids/clay_0-5cm_mean.tif: No such file or directory
#> Error: [rast] file does not exist: /tmp/RtmpgGXl0F/dir1/soilgrids/clay_0-5cm_mean.tif
calc_indicators(x = aoi, indicators = "biome")
#> Simple feature collection with 1 feature and 6 fields
#> Geometry type: POLYGON
#> Dimension:     XY
#> Bounding box:  xmin: -71.80933 ymin: 18.57668 xmax: -71.33201 ymax: 18.69931
#> Geodetic CRS:  WGS 84
#> # A tibble: 1 × 7
#>   WDPAID NAME           DESIG…¹ ISO3  assetid biome                         geom
#>    <dbl> <chr>          <chr>   <chr>   <int> <list>               <POLYGON [°]>
#> 1 478140 Sierra de Nei… Nation… DOM         1 <tibble> ((-71.76134 18.66333, -7…
#> # … with abbreviated variable name ¹​DESIG_ENG

reprex::reprex()
#> ℹ Non-interactive session, setting `html_preview = FALSE`.
#> CLIPR_ALLOW has not been set, so clipr will not run interactively
#> Error in switch(where, expr = stringify_expression(x_expr), clipboard = ingest_clipboard(), : EXPR must be a length 1 vector
```

**Comment by goergen95** [comment]
Thanks for posting. The issue comes from the fact that in your second initialization of the portfolio you don't specify the `add_resources` argument that by default is set to TRUE. From the error message you can see that `calc_indicators()` looks for the `soilgrids` resource in `dir1`:

```r
#> 4: /tmp/RtmpgGXl0F/dir1/soilgrids/clay_0-5cm_mean.tif: No such file or directory
```
The reason that it works with the `biome` resource is that this resource is a vector resource for which the corresponding files are simply added to the portfolio. 

Thus you should re-intialize your portfolio with setting `add_resources=FALSE` and re-querying the `soilgrid` resource to add the correct tileindex.

**Comment by goergen95** [comment]
As mentioned in #92, it is generally recommended, especially if you share the same resource directory across different projects, to re-initialize each portfolio and re-query each resource in every script, in order to make sure that you are always working with the correct spatio-temporal extent for your given AOI.

**Comment by fBedecarrats** [comment]
Hello there. @goergen95 , can you please clarify what you mean by:

> re-query each resource in every script

If it implies to re-download the resource from the source, I think that this was the whole point of #92 : not to have to download again the same resources each time, but reference a resource that is already present locally. I understand that there is a risk of spatio-temporal mismatch with the portfolio, but could it be solved by including some consistency checks when add_resource=FALSE. We should consider the trade-off implied by re-downloading large amounts of data each time. On the long run, this could even enable frequent {mapme.biodiversity} users (e.g. KfW) to store in their own datalake copies of the source data and gain efficiency in the whole process. Don't you think?

**Comment by goergen95** [comment]
Totally agree! Good news is that the behavior you describe is already implemented!

Let's assume the use-case of different projects (so different AOIs) but all sharing the same resource directory in order to avoid having multiple copies of the data on disk.

You, as an analyst, start your script with your specific AOI. How should we decide if for your specific spatio-temporal extent all required files are already downloaded or if there might be some missing files? 

If you simply set `add_resources=TRUE` the package will add all resources it finds *as-is*, not conducting any checks if the extents actually match. This is only useful for single portfolio projects where the spatio-temporal extent never changes, so not the desired behavior for our assumed use-case.

On the other hand, if you set `add_resource=FALSE` and query the resources that **you** need for your current analysis via `get_resources()`, internally, the package will check if all resources matching the spatio-temporal extent of the portfolio are available. It will not re-download existing files but it would download missing files that are not available to match the spatio-temporal extent for your analysis. Eventually, it will re-write the tile indices and you are ready to go for your analysis.

One caveat of this approach, however, is that it actually does not allow simultaneous analysis by you or multiple analysts. Simultaneous - here meaning in the exact same moment - because different portfolios might re-write the tile indices causing a mismatch for either of the analysis in real-time. However, there should be no issues if these analysis would be conducted in sequence sharing the same directory for the resources, because of the behavior explained above.

**Comment by goergen95** [comment]
Btw, I would prefer to continue that high-level discussion over at #92 because this issue is deticated to the explicit problems of the OP.

**Comment by goergen95** [comment]
@Shirobakaidou does my first comment fixes your problem? If that is the case we could close here.

**Comment by Shirobakaidou** [comment]
> @Shirobakaidou does my first comment fixes your problem? If that is the case we could close here.

Hmm not yet completely...
Thank you that the solution given in #92 makes the program fetch resource files from the right location, as shown below
```r
library(sf)
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 7.0.0; sf_use_s2() is TRUE
library(mapme.biodiversity)

dir1 <- file.path(tempdir(), "dir1")
dir2 <- file.path(tempdir(), "dir2")
unlink(list.files(dir1, full.names = TRUE), recursive = TRUE)
unlink(list.files(dir2, full.names = TRUE), recursive = TRUE)
dir.create(dir1)
dir.create(dir2)

aoi <- read_sf(system.file("extdata", "sierra_de_neiba_478140_2.gpkg",
                           package = "mapme.biodiversity"))
ini1 <- init_portfolio(
  x = aoi,
  years = 2015:2020,
  outdir = dir1,
  tmpdir = tempdir(),
  cores = 4,
  verbose = TRUE
) 

getSoil.1 <- get_resources(ini1, resources = "soilgrids",layers = "clay", depths = "0-5cm", stats = "mean")
#> Starting process to download resource 'soilgrids'........
#> Starting to download data for layer 'clay', depth '0-5cm', and stat 'mean'. This may take a while...
getBiome.1 <- get_resources(ini1, resources = "teow")
#> Starting process to download resource 'teow'........

# move resources to a new location
resources <- list.files(dir1, full.names = TRUE)
file.copy(resources, dir2, recursive = TRUE)
#> [1] TRUE TRUE
# remove old location
unlink(resources, recursive = TRUE)

ini2 <- init_portfolio(
  x = aoi,
  years = 2015:2020,
  outdir = dir2,
  tmpdir = tempdir(),
  cores = 4,
  verbose = TRUE
) 

calc_indicators(ini2, "soilproperties", stats_soil = c("mean", "median"), engine = "extract")
#> Warning in new_CppObject_xp(fields$.module, fields$.pointer, ...): GDAL Error
#> 4: /tmp/RtmpaRBV9N/dir1/soilgrids/clay_0-5cm_mean.tif: No such file or directory
#> Error: [rast] file does not exist: /tmp/RtmpaRBV9N/dir1/soilgrids/clay_0-5cm_mean.tif
calc_indicators(ini2, indicators = "biome")
#> Simple feature collection with 1 feature and 6 fields
#> Geometry type: POLYGON
#> Dimension:     XY
#> Bounding box:  xmin: -71.80933 ymin: 18.57668 xmax: -71.33201 ymax: 18.69931
#> Geodetic CRS:  WGS 84
#> # A tibble: 1 × 7
#>   WDPAID NAME           DESIG…¹ ISO3  assetid biome                         geom
#>    <dbl> <chr>          <chr>   <chr>   <int> <list>               <POLYGON [°]>
#> 1 478140 Sierra de Nei… Nation… DOM         1 <tibble> ((-71.76134 18.66333, -7…
#> # … with abbreviated variable name ¹​DESIG_ENG

# Solved with solution in issue #92
ini3 <- init_portfolio(
  x = aoi,
  years = 2015:2020,
  outdir = dir2,
  tmpdir = tempdir(),
  cores = 4,
  add_resources = FALSE,
  verbose = TRUE
)

getSoil.2 = get_resources(ini3, "soilgrids", layers = "clay", depths = "0-5cm", stats = "mean")
#> Starting process to download resource 'soilgrids'........
#> Output file clay_0-5cm_mean.tif exists. Skipping re-download. Please delete if spatial extent has changed.
calc_indicators(getSoil.2, "soilproperties", stats_soil = c("mean", "median"), engine = "extract")
#> Simple feature collection with 1 feature and 6 fields
#> Geometry type: POLYGON
#> Dimension:     XY
#> Bounding box:  xmin: -71.80933 ymin: 18.57668 xmax: -71.33201 ymax: 18.69931
#> Geodetic CRS:  WGS 84
#> # A tibble: 1 × 7
#>   WDPAID NAME           DESIG…¹ ISO3  assetid soilpr…²                      geom
#>    <dbl> <chr>          <chr>   <chr>   <int> <list>               <POLYGON [°]>
#> 1 478140 Sierra de Nei… Nation… DOM         1 <tibble> ((-71.76134 18.66333, -7…
#> # … with abbreviated variable names ¹​DESIG_ENG, ²​soilproperties

getBiome.2 = get_resources(ini3, "teow")
#> Starting process to download resource 'teow'........
calc_indicators(getBiome.2, indicators = "biome")
#> Simple feature collection with 1 feature and 6 fields
#> Geometry type: POLYGON
#> Dimension:     XY
#> Bounding box:  xmin: -71.80933 ymin: 18.57668 xmax: -71.33201 ymax: 18.69931
#> Geodetic CRS:  WGS 84
#> # A tibble: 1 × 7
#>   WDPAID NAME           DESIG…¹ ISO3  assetid biome                         geom
#>    <dbl> <chr>          <chr>   <chr>   <int> <list>               <POLYGON [°]>
#> 1 478140 Sierra de Nei… Nation… DOM         1 <tibble> ((-71.76134 18.66333, -7…
#> # … with abbreviated variable name ¹​DESIG_ENG
```

You mentioned in the comment that
"On the other hand, if you set add_resource=FALSE and query the resources that you need for your current analysis via get_resources(), internally, the package will check if all resources matching the spatio-temporal extent of the portfolio are available. It will not re-download existing files but it would download missing files that are not available to match the spatio-temporal extent for your analysis. Eventually, it will re-write the tile indices and you are ready to go for your analysis."

I tried to apply this solution on a changed spatial extent but it didn't work...
Did I do it in the correct way? Where do you see the problem?

```r
# Not Solved: when updating spatial extent
bbox = st_bbox(c(xmin=44.14, xmax=44.24, ymax=-24.52, ymin=-24.62), crs=st_crs(4326)) %>%
  st_as_sfc() %>% st_as_sf
aoi2 = st_make_grid(bbox, n=c(2,2)) %>% st_as_sf()

ini4 <- init_portfolio(
  x = aoi2,
  years = 2015:2020,
  outdir = dir2,
  tmpdir = tempdir(),
  cores = 4,
  add_resources = FALSE,
  verbose = TRUE
)

getSoil.3 = get_resources(ini4, "soilgrids", layers = "clay", depths = "0-5cm", stats = "mean")
#> Starting process to download resource 'soilgrids'........
#> Output file clay_0-5cm_mean.tif exists. Skipping re-download. Please delete if spatial extent has changed.
calc_indicators(getSoil.3[1,], "soilproperties", stats_soil = c("mean", "median"), engine = "extract")
#> Error : [crop] extents do not overlap
#> Warning in .read_raster_source(shp, tindex, rundir): Error : [crop] extents do not overlap
#> Simple feature collection with 1 feature and 2 fields
#> Geometry type: POLYGON
#> Dimension:     XY
#> Bounding box:  xmin: 44.14 ymin: -24.62 xmax: 44.19 ymax: -24.57
#> Geodetic CRS:  WGS 84
#> # A tibble: 1 × 3
#>   assetid soilproperties                                                       x
#>     <int> <list>                                                   <POLYGON [°]>
#> 1       1 <tibble [1 × 1]> ((44.14 -24.62, 44.19 -24.62, 44.19 -24.57, 44.14 -2…

getBiome.3 = get_resources(ini4, "teow")
#> Starting process to download resource 'teow'........
calc_indicators(getBiome.3[1,], indicators = "biome")
#> Simple feature collection with 1 feature and 2 fields
#> Geometry type: POLYGON
#> Dimension:     XY
#> Bounding box:  xmin: 44.14 ymin: -24.62 xmax: 44.19 ymax: -24.57
#> Geodetic CRS:  WGS 84
#> # A tibble: 1 × 3
#>   assetid biome                                                                x
#>     <int> <list>                                                   <POLYGON [°]>
#> 1       1 <tibble [1 × 2]> ((44.14 -24.62, 44.19 -24.62, 44.19 -24.57, 44.14 -2…


reprex::reprex()
#> ℹ Non-interactive session, setting `html_preview = FALSE`.
#> CLIPR_ALLOW has not been set, so clipr will not run interactively
#> Error in switch(where, expr = stringify_expression(x_expr), clipboard = ingest_clipboard(), : EXPR must be a length 1 vector
```

**Comment by goergen95** [comment]
Ok, so in principle moving the resources to a new location works which in my understanding was the initial question in this issue. Looking at the code for downloading soilgrid data I see that we currently only check for the filenames not the spatial extent. That is also indicated in the the warning message which asks to delete the soilgrid resources if the spatial extent has changed. The reason is that soilgrid data layers are not distributed in tiles.

**Comment by Shirobakaidou** [comment]
Yes right, Sorry, extending aoi should go to a new issue, the problem in this issue is solved:)
