### ISSUE TITLE
Drivers of Deforestation

### ISSUE THREAD

**Issue by goergen95** [mapme-initiative/mapme.biodiversity#148]
# Drivers of deforestation

## Definition of research question

What are the direct drivers of deforestation?

## Definition of the indicator

The indicator is meant to shed some light on the causes/drivers of observed deforestation. [Curtis et al. (2018)](https://www.science.org/doi/abs/10.1126/science.aau3445#supplementary-materials) 
suggested an approach to grasp the concept of direct drivers of deforestation by training decision tree models based
on selected spatial covariates of deforestion drivers. Based on visual inspection of VHR imagery, they labeled 
about 5000 training chips, each of a size of 10 x 10 km, where forest loss was present in GFC.
The assigned classes are:
- commodity-driven deforestation
- shifting agriculture
- forestry
- wildfire
- urbanization

The set of predictors consists of selected covariates of deforestation aggregated to the 10x10 km target resolution.
The predictors are:
- population in 2000
- population in 2015
- population difference
- treecover in 2000
- total treecover loss 2000-2015
- total treecover gain 2000-2015
- difference between oldest and most recent loss year
- treecover loss and MODIS fire location overlap
- fire brightness
- fire temperature
- total number of fires
- ESA Global Consensus Land Cover classes for forest types

Decision tree models for each of the 5 classes within 7 reference regions were trained based on the labeled data set
and the predictors. Then, the models were used to predict the dominant driver of deforestation for each 10x10 km 
grid cell for the whole globe were forest loss was observed.
Overall Accuracy was 89% ranging from 55% for urbanization to 94% for commodity-driven deforestation.
The final dataset is a raster set with 10x10 km resolution indicating the dominant driver of deforestaion
for the 2000 to 2015 (2018) time period.

## Possible data-sources

- [Classifying drivers of global forest loss](https://www.science.org/doi/suppl/10.1126/science.aau3445/suppl_file/aau3445-data-s3.tif)

## Spatio-temporal resolution

The spatial resolution is 10 x 10 km. The data set consists of a single raster layer
caring inforatiom about the main driver of deforestation of the respective grid 
cell in the period 2000-2018, e.g. the data is not time dynamic.

## Accessibility

The raster data set can directly be downloaded from the [publication website](https://www.science.org/doi/suppl/10.1126/science.aau3445/suppl_file/aau3445-data-s3.tif)

**Comment by Jo-Schie** [comment]
Thanks @goergen95 . I think this is a great Ressource but I wonder how helpful it is for our portfolio. I think we would need to check it together with the wdpa database. 

Pros is definitely that it is a low hanging fruit. Cons is that it is not updated up to 2023. 

We were also discussing this in light of the esa biomass data which might be used to grasp better the nature of change trends (see the wiki on new indicators, currently point 12). Happy to hear your opinion on this @fBedecarrats . the esa data might be used to not only identify possible drivers but also subsequent land use. Not sure if there is some literature out there doing something like that but it's worth looking.

**Comment by goergen95** [comment]
Thanks for your valuable feedback! I agree that the Curtis et al. data might not be fit-for-purpose because of its very coarse spatial resolution and since it is static over time. 
The resource you are referring to should be [Vancutsem et al (2021)](https://www.science.org/doi/10.1126/sciadv.abe1603).  The most important distinction is that Vancutsem et al investigate forest cover transitions. This is actually a very different concept from drivers of deforestation and we should be clear what we are talking about. 
In light of this, I am planning to open another issue explicitly dedicated to forest transitions. I expect the Vancutsem et al resource to be of higher value for the package and its users, but it is also way more complex to derive actionable and easy-to-understand indicators.

**Comment by fBedecarrats** [comment]
Hi @goergen95 and @Jo-Schie! My understanding is that most studies sudying PA effectiveness against deforestation published after Curtis et al. 2019 either use this dataset as matching variable and/or covariate, or produce an equivalent dataset for their area of interest.  I will do a quick systematic review on Google Scholar to check wether this is true or just a biaised perception on my side.
Fritz et al. 2022 updated this dataset: https://www.frontiersin.org/articles/10.3389/fcosc.2022.830248/full?field=&journalName=Frontiers_in_Conservation_Science&id=830248
I am not sure that the extent is as broad as the original one. I will try to check this this week.

**Comment by goergen95** [comment]
Here is a quick summary of the method used by Fritz et al. highlighting the difference to the data set by Curtis et al:
- dominant drivers of deforestation between 2008-2019 between 30°N to 30°N
- 150K VHR image chips labeled by a crowd-sourcing campaign with an increased spatial resolution of 1 km²
- more fine-graind classes including:
  - subsistence agriculture
  - commercial agriculture
  - commercial palm plantations
  - pasture
  - managed forestry
  - mining and oil extraction
  - wildfire
  - other natural disturbances

If I am not mistaken, no publicly available raster data set has been produced yet. But the original campaign data was published [here](https://www.nature.com/articles/s41597-022-01227-3).  Maybe we need to discuss what information we are actually interested in retrieving? If we are interested in pixel-wise information, I guess it would be best to think in the direction of tree cover / land cover transitions. If we are more interested in the (proportions of)  dominant driver(s) per asset / PA I think the data sets we are discussing here are quite suitable?

**Comment by Jo-Schie** [comment]
Thank you very much both. The publication looks promising and since the spatial resolution is more close to what we need, I think it would be a good option. What I'm unsure however, is that we can access to this data and I'm not sure if it is continuously updated. That is a general problem for the sustainability in this open data/open source context. I will try to write an email to the corresponding author and put you in CC to further clarify this question.

**Comment by Jo-Schie** [comment]
Fyi @karpfen and @melvinhlwong : outcome of our discussion via webex with @fBedecarrats and @goergen95 and @Jo-Schie:

**Regarding an Integration of  [JRC/TMF](https://forobs.jrc.ec.europa.eu/TMF/data.php)** 
**Pros**: 
This seems to be the most likely option from a technical point of view (see the corresponding paper [here](https://www.science.org/doi/10.1126/sciadv.abe1603). Using the dataset will enable us to advance in several thematic areas: For impact evaluation it can improve matching procedures by including similar forest trend data as matching variables. For planning and monitoring purposes the dataset can give more insights into actual forest dynamics in comparision to the Hansen et al. Binary approach. It thus indicates more closely the actual forest trends and can increase the comparability and the differences of the very distinct trends amongst regions.  Another advancement can be adchieved because the dataset can be used to distinguish between temporary disturbances (e.g. fire) and longer-term conversion as well as map forest regrwoth. Another strong argument in favor is that this data-set will be updated continously. 
**Cons**
The dataset is, however, less intuitive for users with a non-technical background and lower data literacy due to the multitude of categories and possible pathways. It is also trickier when calculating zonal statistics since degradation trends can not be summed up while permanent loss areas can. 
**Take-Away** 
We would need to dig deeper in the concepualization of adequate data products and associated processing routines. 

**Regarding an Integration of  [Fritz el al data](https://www.frontiersin.org/articles/10.3389/fcosc.2022.830248/full)**
**Pros**
This dataset is very intuitive to use. It's main strength is to improve matching (same argument as above) and especially assist during the project preparation fase (more adequate understanding of the local threats). 

**Unclear**
 (to be discussed in a meeting with the authors)
* It seems that the dataset is not yet provided as a wall-to-wall data product. We need to contact the authors on the possibility of obtaining it. 
* It is unclear if the dataset will or can be updated in the future (i.e. with low further input). 
* It is unclear how the dataset could be integrated in the package since it is not hosted online e.g. as tiles and it remains unclear whether the authors will make this dataset public in an easy digestible way. 

**Other Aspects**
* Regarding the usefullness one could argue that there is no need for a continous update of this dataset since drivers might not change that fast locally. However there might be cases where this is not true (e.g. adoption of pasture of shifting cultivation in parts of Latin America). Thus the dataset might be usefull even if not updated (at least for a limited amount of time). 
*  An alternative could be using data from [Curtis et al 2018 ](https://www.science.org/doi/10.1126/science.aau3445) which has a similar purpose, however fewer categories and a considerably lower spatial resolution (10x10 km) compared to 1x1 km from the proposed dataset. Qith a quick check I could not find, however, the data online.

**Comment by goergen95** [comment]
Please also see  #149 for an dedicated issue for adding the TMF as a resource to the package.

**Comment by Jo-Schie** [comment]
So the data is online. 

https://zenodo.org/record/7997945
https://zenodo.org/record/7997885

Ad soon as there is time we should envisage putting this to development

**Comment by goergen95** [comment]
I opened a PR that includes the new resource and and indicator that is ready for review. Currently the indicator calculates the total and relative fraction of deforestation drivers per asset.
