### ISSUE TITLE
get_resources for global mangrove watch (gmw) is very long

### ISSUE THREAD

**Issue by fBedecarrats** [mapme-initiative/mapme.biodiversity#170]
GMW is disseminated with only one file per year for the entire world. 
get_resources fetches the whole data (~180Mo per available year) and converts the source data to geopackage **for the whole world** irrespective of the perimeter used to define the portfolio. The output geopackages are very heavy and the process takes ~3-4 minutes to complete for each year and the output file size is about 1GB for each year.
With @lenaigmoign , we were ondering if it was not possible to spatially filter for the area of interest defined in the init_portfolio to focus the geopackage creation on this AOI.

**Comment by goergen95** [comment]
From the current source, GMW data is distributed as one zip file per year containing a Shapefile. We convert this to Geopackage internally. Since you already will have downloaded the global data set, we made the decision to also convert at to Geopackage at the global level. This is the case for most vector resources currently integrated in the package (e.g. NASA FIRSMS).

**Comment by goergen95** [comment]
Open to suggestions to change that behavior if it makes sure that always the correct extent is processes and does not require re-downloading the original data source.

**Comment by goergen95** [comment]
Some more context: The idea is that you download resources once and maybe share between different portfolio analysis. If you change your extent only slightly, if there is missing data, the package will download this missing data and process it to the appropriate format. Currently, mainly because sources are distributed in very different ways in very different formats, the package takes an pragmatic approach to download the least amount of data necessary to match a given portfolio (e.g. in this case only the matching years are downloaded). The actual benefit comes if you store the resources in a common place and query different portfolios against it. In that case, for a later portfolio analysis none of the GMW data will have to be downloaded nor processed.

**Comment by goergen95** [comment]
Using GDAL directly to translate to GeoPackage instead running through sf I see a reduction factor of about 2 in processing time:

``` r
library(sf)
#> Linking to GEOS 3.11.1, GDAL 3.6.2, PROJ 9.1.1; sf_use_s2() is TRUE

url <- "https://wcmc.io/GMW_2010"
rundir <- file.path(tempdir(), "mapme")
dir.create(rundir)
zip <- file.path(rundir, "gmw.zip")
download.file(url, zip)


utils::unzip(
  zipfile = zip,
  exdir = rundir
)

shp <- list.files(rundir, "*.shp$", full.names = TRUE)

gpkg_sf <- file.path(rundir, "sf.gpkg")
gpkg_gdal <- file.path(rundir, "gdal.gpkg")

system.time({
  data <- read_sf(shp)
  write_sf(data, gpkg_sf)
})
#>    user  system elapsed 
#>  45.103   3.450  48.560

system.time({
  gdal_utils( util = "vectortranslate", shp, gpkg_gdal)
})
#>    user  system elapsed 
#>  25.068   1.908  26.991

unlink(rundir, recursive = TRUE, force = TRUE)
```

<sup>Created on 2023-06-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
