### ISSUE TITLE
Introduce more consistency in how the output data is presented to the user. 

### ISSUE THREAD

**Issue by Jo-Schie** [mapme-initiative/mapme.biodiversity#21]
@Ohm-Np  and @goergen95 

Working with the outputs, I saw that the output comes in very different shapes. I understand that this is necessary e.g. because some data comes with a time-dimension and hence it is advantegous to put it into a longtable format. 

Nevertheless I think we should be more consistent how we present the user with multiple indicators from the same asset. Currently you have two different approaches. The SRTM data shows for example two output columns (tri and elevation) and the user unnests them separatly. The soil data in contrast presents the user with a single column that, when unnested, presents the user with a longtable with multiple indicators that he has to transform to wide. 

I'm not a 100% sure which approach is better but I think we should be consistent and then tell the user in the quick start guide on how to work with the data (how to unnest it and eventually transform it to wide format). Would be great to have your opinion on that.

**Comment by Jo-Schie** [comment]
maybe it would help to define what the main structures are. like

- different indicators from same source.
- different stats for same indicator from same source.
- time-dimension (definitly long-format).

**Comment by goergen95** [comment]
I see your point to some extent. The issue is that indicators will be very different thus making it a requirement that the results for indicators will look different. In your example above there is one important distinction, however. In the current implementation we defined `tri` and `elevation` as two distinct indicators that for obvious reasons share the same input resource (`srtmdem`). Since they are treated as different indicators, they will each end up in their respective nested column. This is different how we implemented the indicator `soilproperties`. This is treated as one indicator where potentially very different user-defined collection of the `soilgrid` resource are covered. That is the reason why all different `layers` show up in  within a single nested column. The alternative would be to implement each `layer` provided by soilgrids as their own respective resource AND indicator, which in my eyes unnecessarily increase complexity both for users and us maintaing the source code. 

Concerning the general output structure, I would agree with you that more or less sharing the same structure between indicators would be beneficial. We could, for example, agree that all indicators should be delivered in long format. However, consider the case of the `elevation` indicator. It is a time invariant indicator that, with the current implementation, if unnested does not increase the row number of the portfolio object. If we provided it in long-format provided a user requested the calculation of `"mean", "median","sd"` unnesting the indicator would increase the row-number by a factor of 3. 

I am not sure about the best approach here but I agree that we should define some rules that then have to be applied strictly in order not to confuse users.

**Comment by Jo-Schie** [comment]
thanks for clarification. Maybe one easy to handle solution could be that, if the data comes from the same source, then it should end up in the portfolio object only as one list in longformat. That would mean that e.g. for the GFW data, emissions and forestloss would be in the same table (you may call it super-long format). then the user only needs to unnest one list that contains all relevant indicators. 

Otherwise I think it becomes very blurry. Why is e.g. ph content of soils and clay content in the same list/table although they are covering different indicators/variables? If we were to apply the logic from the GFW data we would put it at least in two different lists.  soil itself is not a variable but rather a category. To go even further one could argue that clay content in the topsoil (0-5cm) is a different variable then clay content in the lower soil strata... 

For the case of GFW the user is presented with two lists that he/she needs to unnest seperatly whereas for soil all is in the same table... Therefore the suggestion to put it all into a single list. Then a biodiversity object would have the attributes

* .asset_id
* forest
* accessibility
* soil
* precipitation
* ...

I think that is clearer and easier to communicate where the user can find the data from the ressource in the end. Maybe the lists could also be just named according to the ressources. That would make it even more consistent.

**Comment by goergen95** [comment]
thanks for your ideas. I suggest that we put this issue on the agenda for the next meeting so that we can brainstorm on the best solution in person.
Some relevant notes related to your previous comment:
- if all indicators that rely on the same resources would end-up in the very same column users can not really fine-tune their analysis. Consider the GFW indicators where we implemented treecover, emissions AND treeloss (which covers both of the previous two indicators). treecover only relies on treecover2000 and lossyear while emissions also requires the greenhouse resource. What if users are only interested in the treecover?
- what is the big deal with unnesting more than one column? The nesting approach is somewhat mandatory unless we define a common structure which applies to ALL current and future indicators. If users are interested in all GFW indicators in one run the treeloss indicator was implemented for that case (see above)
- the indicator for soil is called `soilproperties` and its variables depend on what soil data layers users have previously chosen to download. We did not define soil as a variable, however, all data layers available by the `soilgrid` resource are related and follow exactly the same processing logic. 
- we cannot share the same names between resources and indicators otherwise the documentation will get really messy
- also please notw that we document the table format of each indicator explaining to potential users what to expect as output from the functions

**Comment by goergen95** [comment]
Just one more aspect to clarify why we chose the nested column approach: depending on the settings users chose for both resources and indicators (e.g. which years to include in the analysis or which statistics to calculate) the outputs will vary substantially even for the same indicator not to speak of different indicators. Because the shape of an indicator is hard to predict, nested columns allow us to support arbitrary shapes for all indicators. (That does not mean that we should not take substantial effort to make it easy for users to understand what to expect when they call a certain indicatoe function)

**Comment by goergen95** [comment]
Please see this [paragraph](https://github.com/mapme-initiative/mapme.biodiversity/blob/e6cad8d00dabfc59f58df5974cd8ed9bdce079ed/vignettes/contributing.Rmd#L559) for suggestion. That would mean we have to adapt the tri and elevation indicators. Happy to discuss this

**Comment by goergen95** [comment]
Hi @Jo-Schie, I tried to harmonize how the indicators are returned and also included examples of how to calculate each indicator plus how the output looks like in the online documentation. If you head over to the [indicators section](https://mapme-initiative.github.io/mapme.biodiversity/reference/index.html#indicators) and click through the indicators you can see how the output now looks for each of them. Happy to receive your feedback here.
