### ISSUE TITLE
Unused argument `add_resources` in function `init_portfolio()`

### ISSUE THREAD

**Issue by Shirobakaidou** [mapme-initiative/mapme.biodiversity#238]
Hello Darius, 

It seems that `add_resources` is now an unused argument for the function `init_portfolio()`. I used to set `add_resources=FALSE` to download additional raster files when the extent of the study area changes, or to avoid errors if the directory path to the existing raster changes.

What is the current alternative to this argument?
In case it is now abandoned, what if I want to download only additional data to the existing ones when the study area changes?

Thank you for your reply,
Kemeng

**Comment by goergen95** [comment]
Hi, 
it is the default behavior of the package to download only those resources that are not already present in `outdir`. 
What has changed is that you now *must* run `get_resources()` prior to an indicator calculation in order to make sure that the internal data catalog is up to date. This applies to different analysis sharing the same output directory.

Hope this helps, let me know if you run into further issues.

**Comment by Shirobakaidou** [comment]
Perfect, thanks for the quick response!
