### ISSUE TITLE
Worldpop server does not integrate with GDAL

### ISSUE THREAD

**Issue by goergen95** [mapme-initiative/mapme.biodiversity#265]
When querying worldpop layers with GDAL I see:

```bash
> gdalinfo /vsicurl/https://data.worldpop.org/GIS/Population/Global_2000_2020/2019/0_Mosaicked/ppp_2019_1km_Aggregated.tif

ERROR 1: Range downloading not supported by this server!
gdalinfo failed - unable to open '/vsicurl/https://data.worldpop.org/GIS/Population/Global_2000_2020/2019/0_Mosaicked/ppp_2019_1km_Aggregated.tif'.

```

So we cannot get the data from there via GDAL. I see three options:
- 1) Find another source for the worldpop layers
- 2) Develop a work-around in the package code to download locally
- 3) Ask worldpop to change their server settings

**Comment by goergen95** [comment]
There is Meta's HighRes population layer on AWS [here](https://registry.opendata.aws/dataforgood-fb-hrsl/) but I could not access the data yet without authentication.

**Comment by fBedecarrats** [comment]
Hi! I do not understand how to check the years for which the CIESIN/META dataset is available. I looked at [the general documentation](https://ai.meta.com/blog/mapping-the-world-to-help-aid-workers-with-weakly-semi-supervised-learning/) and the working papers [here] and [there](https://arxiv.org/pdf/1712.05839). It is not clearly stated but I think that the data starts in 2019. The data is also [accessible on HDX](https://data.humdata.org/organization/meta?res_format=GeoTIFF&q=&sort=last_modified%20desc&ext_page_size=25), but only from 2019.
I think that it would be good to have @melvinhlwong 's opinion on this, but if this is confirmed, I don't think that Meta's HighRes population layer could replace Worldpop for the standard use case of mampe.biodiversity (ie. protected area impact evaluation). Impact evaluation require covariates that are anterior and/or not affected by the treatment. As put by Noah Greifer (MatchIt package author):

> "To estimate total causal effects, all covariates must be measured prior to treatment (or otherwise not be affected by the treatment). " ([source](https://kosukeimai.github.io/MatchIt/articles/MatchIt.html#planning))

So in order to assess protected area impact, we need population estimates that precede the protected areas' creation. This is possible with Worldpop that provides estimates from 2000 onwards.

**Comment by goergen95** [comment]
Agreed that most use-cases for the package require the time-series of Worldpop. I had a similar issue with one of the new carbon resources which are not directly readable from the source location. I solved it with downloads to a temporary location (see [here](https://github.com/mapme-initiative/mapme.indicators/blob/1179729f97d04bf9b5463d2d9ecf8a05965387c0/R/get_carbon.R#L124)) and would suggest to take the same path with WorldPop data. That would mean, however, that this data and related indicators are not compatible with "online" usage because they always require you to download the full data set even if you query just a handful of PAs with limited geographic extent.

**Comment by fBedecarrats** [comment]
We should maybe remove the Worldpop example from the Quickstart page then: https://mapme-initiative.github.io/mapme.biodiversity/articles/quickstart.html
at least until we have a more efficient procedure to showcase. Don't you think?

**Comment by goergen95** [comment]
Please find b76a677951da13a88e71cdb6b408b94f793d8b94 that will create temporary downloads for layers not already present in the path indicated by `outdir`. Next steps for the `dev` branch would be to update the vignette as per your last comment.
