### ISSUE TITLE
Enable manual addition of resources

### ISSUE THREAD

**Issue by fBedecarrats** [mapme-initiative/mapme.biodiversity#92]
When using the package I wanted to manually load resources in two situations:
- I had loaded global forest watch tiles with the CRAN version of {mapme.biodiversity}. Then I switched to the github version and these resources were named differently and had to be stored in a different subfolder. Downloading these resources is long and I suspect that GEE slows down the transfer speed after several downloads.
- The get_resources() command did not work for me for nasa_srtm, but it was quite straghtforward to download the tiles directly from my pod with download_file()
For these cases, I used the following script to index these resources that I had added manually :
```r
outdir = "data_s3/mapme"
resource <- "nasa_srtm"
rundir <- paste(outdir, resource, sep = "/")
tindex_file <- file.path(rundir, paste0("tileindex_", resource, ".gpkg"))

downloaded_files <- list.files(rundir, full.names = TRUE)
footprints <- lapply(downloaded_files, function(file) {
  tmp <- rast(file)
  footprint <- st_as_sf(st_as_sfc(st_bbox(tmp)))
  st_geometry(footprint) <- "geom"
  footprint$location <- sources(tmp)
  footprint
})
footprints <- do.call(rbind, footprints)
write_sf(footprints, dsn = tindex_file)
```
I wonder if it would not be useful to include such a function in the package.

**Comment by Jo-Schie** [comment]
This seems to me to be quiet similar to [#84](https://github.com/mapme-initiative/mapme.biodiversity/issues/89) https://github.com/mapme-initiative/mapme.biodiversity/issues/89

**Comment by fBedecarrats** [comment]
> This seems to me to be quiet similar to #89

Yes, indeed: it correspond to the same feature request. The idea would be to manually download some rasters (as a matter of fact, the idea is often to re-use the existing rasters), and let the package re-build all the .gpkg it needs to index it correctly.

**Comment by Jo-Schie** [comment]
just as a comment on this issue. @Shirobakaidou also faced this issue when we just moved some local files because the disk ran out of space after downloading 40 GIG of FIRMS data. I guess it would be a cool feature for new developments. I am not sure though, if, as a workaround, one could just respecify the path where the downloaded data is stored in the object that is created with `init_portfolio`. I think we discussed this once @goergen95, right?

**Comment by fBedecarrats** [comment]
> just as a comment on this issue. @Shirobakaidou also faced this issue when we just moved some local files because the disk ran out of space after downloading 40 GIG of FIRMS data. I guess it would be a cool feature for new developments. I am not sure though, if, as a workaround, one could just respecify the path where the downloaded data is stored in the object that is created with `init_portfolio`. I think we discussed this once @goergen95, right?

Hi, I am not sure that the FIRMS data in itself is the problem. If I remember correctly, the bunch of the data volume is due to the size of the `.gpkg`s created after data download.

**Comment by goergen95** [comment]
Hi all, 
I think we basically have the desired behavior already implemented. I produced a small example to show how you can get something like this use case to work. I admit it might be a little bit confusing and needs better documentation (e.g. as raised in #91).
``` r
library(sf)
#> Linking to GEOS 3.11.1, GDAL 3.6.1, PROJ 9.1.1; sf_use_s2() is TRUE
library(mapme.biodiversity)

dir1 <- file.path(tempdir(), "dir1")
dir2 <- file.path(tempdir(), "dir2")
dir.create(dir1)
dir.create(dir2)

aoi <- read_sf(system.file("extdata", "sierra_de_neiba_478140_2.gpkg",
                           package = "mapme.biodiversity"))

portfolio1 <- init_portfolio(
  x = aoi,
  years = 2022,
  outdir = dir1,
  tmpdir = tempdir(),
  add_resources = FALSE,
  cores = 1,
  verbose = FALSE
) 

portfolio1 <- get_resources(
  portfolio1, 
  "soilgrids",
  layers = "clay", 
  depths = "0-5cm", 
  stats = "mean"
)

# move resources to a new location
resources <- list.files(dir1, full.names = TRUE)
file.copy(resources, dir2, recursive = TRUE)
#> [1] TRUE
# remove old location
unlink(resources, recursive = TRUE)

  # this will fail because the resources are now longer available
calc_indicators(portfolio1, "soilproperties", stats_soil = c("mean", "median"), engine = "extract")
#> Error: Cannot open "/tmp/Rtmp1cWE33/dir1/soilgrids/tileindex_soilgrids.gpkg"; The file doesn't seem to exist.

# this will fail because the resources still point towards "dir1"
portfolio2 <- init_portfolio(
  x = aoi,
  years = 2022,
  outdir = dir2,
  tmpdir = tempdir(),
  add_resources = TRUE, # note that we added the resources as is
  cores = 1,
  verbose = FALSE
) 
calc_indicators(portfolio2, "soilproperties", stats_soil = c("mean", "median"), engine = "extract")
#> Warning: /tmp/Rtmp1cWE33/dir1/soilgrids/clay_0-5cm_mean.tif: No such file or
#> directory (GDAL error 4)
#> Error: [rast] file does not exist: /tmp/Rtmp1cWE33/dir1/soilgrids/clay_0-5cm_mean.tif

# this will run sucessfully because the tile index is newly written
# existing resourse files will not be re-downloaded
portfolio3 <- init_portfolio(
  x = aoi,
  years = 2022,
  outdir = dir1,
  tmpdir = tempdir(),
  add_resources = FALSE, # note that we did not add the resources
  cores = 1,
  verbose = FALSE
) 
portfolio3 <- get_resources(
  portfolio3, 
  "soilgrids",
  layers = "clay", 
  depths = "0-5cm", 
  stats = "mean"
)
calc_indicators(portfolio3, "soilproperties", stats_soil = c("mean", "median"), engine = "extract")
#> Simple feature collection with 1 feature and 6 fields
#> Geometry type: POLYGON
#> Dimension:     XY
#> Bounding box:  xmin: -71.80933 ymin: 18.57668 xmax: -71.33201 ymax: 18.69931
#> Geodetic CRS:  WGS 84
#> # A tibble: 1 × 7
#>   WDPAID NAME           DESIG…¹ ISO3  assetid soilpr…²                      geom
#>    <dbl> <chr>          <chr>   <chr>   <int> <list>               <POLYGON [°]>
#> 1 478140 Sierra de Nei… Nation… DOM         1 <tibble> ((-71.76134 18.66333, -7…
#> # … with abbreviated variable names ¹​DESIG_ENG, ²​soilproperties
```

<sup>Created on 2023-01-20 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>


A little explanation:
- the first example will fail because in the attributes of the `portfolio1` object still point towards `dir1` to find the tile index. This will produce an error because this file no longer exists. 

- The second approach actually finds the tile index in its new location `dir2`, but this tile index is not newly written so its entries still point towards `dir1` where the files no longer exist. 

- What works is the third approach, where the portfolio is initiated without adding the resources from the start and re-querying the download of the resource. This will not actually re-download any resources that are already present but it will re-write the tileindex so it points towards `dir2`. 
 
Thus, the recommended approach to conduct analysis e.g. for different AOIs is always to initiate a new portfolio and re-query its resources. This also has the benefit that if you change the spatio-temporal extent of your AOI, missing files will actually be downloaded.

**Comment by Shirobakaidou** [comment]
@goergen95 After relocating the resource raster files, the calculation of indicators "biome", "ecoregion" and "mangroves_area" don't yield any error. Would it be possible to make the calculation of other indicators behave in the same way as these three?

**Comment by goergen95** [comment]
Could you please open a new issue with more information (e.g. error messages) and ideally minimal reproducible examples for the indicators where the above mentioned approach does not work?

**Comment by goergen95** [comment]
Originally posted comment at #130 further explaining the packages behavior for the `add_resources` argument:

Totally agree! Good news is that the behavior you describe is already implemented!

Let's assume the use-case of different projects (so different AOIs) but all sharing the same resource directory in order to avoid having multiple copies of the data on disk.

You, as an analyst, start your script with your specific AOI. How should we decide if for your specific spatio-temporal extent all required files are already downloaded or if there might be some missing files?

If you simply set add_resources=TRUE the package will add all resources it finds as-is, not conducting any checks if the extents actually match. This is only useful for single portfolio projects where the spatio-temporal extent never changes, so not the desired behavior for our assumed use-case.

On the other hand, if you set add_resource=FALSE and query the resources that you need for your current analysis via get_resources(), internally, the package will check if all resources matching the spatio-temporal extent of the portfolio are available. It will not re-download existing files but it would download missing files that are not available to match the spatio-temporal extent for your analysis. Eventually, it will re-write the tile indices and you are ready to go for your analysis.

One caveat of this approach, however, is that it actually does not allow simultaneous analysis by you or multiple analysts. Simultaneous - here meaning in the exact same moment - because different portfolios might re-write the tile indices causing a mismatch for either of the analysis in real-time. However, there should be no issues if these analysis would be conducted in sequence sharing the same directory for the resources, because of the behavior explained above.

**Comment by goergen95** [comment]
Appreciating that the current implementation seems to rather confuse than being helpful and considering that real-time simultaneous analysis would be a very nice feature I see a possible way forward.

If we handle the checks if resources are available on a per-session basis in the package internals we could get rid of the `add_ressources` argument altogether and allow for real-time simultaneous analysis using the same resource directory.

This would, however, necessitate users to always follow the same pattern for every script (portfolio initialization -> requesting resources -> indicator calculations), e.g.:

```r
init_portfolio(aoi) %>%
  get_resources("resource") %>%
  calc_indicators("indicator")
```

The only downside is that users would not be able to skip the `get_resources()` step anymore, if they know that the complete extent is available. But overall, this solution would eliminate a substantial source of potential errors, confusion and frustration. Do you have any thoughts?

**Comment by fBedecarrats** [comment]
> If we handle the checks if resources are available on a per-session basis in the package internals we could get rid of the `add_ressources` argument altogether and allow for real-time simultaneous analysis using the same resource directory.

I think there is a typo here: it is `get_resources` and not `add_resources`, right?

**Comment by fBedecarrats** [comment]
Now I get that I initially misunderstood your answer with example above ([#issuecomment-1398104918](https://github.com/mapme-initiative/mapme.biodiversity/issues/92#issuecomment-1398104918)). My understanding was that the "get" in `get_resources()` litterally meant "download the tiles", and the fact that the `add_resources` is a parameter of init_portfolio() and not `get_resources()` somehow confused me. I think that the mental model that I built when reading "initialize portfolio" and "get resources" is different to how the package actually handles the underlying data assets.

**Comment by Jo-Schie** [comment]
@goergen95:  Could it be an option to simply write a little helper function like "link_resources" that allows users to link already downloaded resources or moved resources? 

Maybe that is the easiest way given that the function would be easy to find in the package documentation and it might be quite a common use-case. 

For the case where several people work on one Ressource/database simultaneously it might be also an option to store the indexfile in the current working directory rather then in the Ressource directory. Like this, user could have different indexfiles.

On a side note: it would be maybe more intuitive to call it get_database or create_database rather then get_resources. Not sure if "resources" is a common term in English in the data science context...

**Comment by goergen95** [comment]
Is this still an open issue? One could argue that with the new register method now you are actually able to add arbitrary data to your workflow, right?
