### ISSUE TITLE
Provide more guidance about projections and units

### ISSUE THREAD

**Issue by fBedecarrats** [mapme-initiative/mapme.biodiversity#93]
My suggestion here might still need some precision and it might partly apply to the [mapme.protectedareas](https://github.com/openkfw/mapme.protectedareas) repo.
The fact that {mapme.biodiversity} works with non-projected data (EPSG:4326) might be confusing in some cases. For instance, users will usually use projected data to generate honeycomb (like you [when creating your grid in mapme.protectedareas](https://github.com/openkfw/mapme.protectedareas/blob/main/code/processing-scripts/01_grid_creation.R)). Users would also use projected data if they want to compute spatial statistics on their PAs or the perimeters targeted by some development or conservation projects. A recommendation about how to deal with this back and forth between projected and non-projected data would be useful.
Moreover, computing indicators with non projected data raises interrogations regarding the units of the metrics compuded. For instance, what is the unit of the result of `calc_indicators(indicators = "treecover_area")`?
Feel free to close this issue if it seems not so relevant (in fact I was looking for a discussion section, but it seems that you haven't opened one for this repo).

**Comment by Jo-Schie** [comment]
I think units are given in the description of the indicators. In the case of GFW data it's hectare ... as to the reference system I am unsure where to put your suggestion in the documentation. Generally I would say users do not need to worry about the projection systems because the package handles them automatically. 

I am not 100% sure though how the internals of the package work regarding area calculation. Maybe that's what you are referring to? So that users understand which CRS is used to calculate areas?

**Comment by fBedecarrats** [comment]
My bad: the information on the units was there all the time (in the indicators definition). I just didn't see it (too late in the night). I'm closing the issue and sorry for the trouble.
